### ISSUE TITLE
Cannot put useable items into shelves or displays! Was trying to display my elytra, and spyglass. Neither are able to go into the display without trying to equip to my person. 

### ISSUE THREAD

**Issue by CybertronionGame** [OopsOnlyDelta/redeco#8]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by OopsOnlyDelta** [comment]
Both appear to be working when I test. However, I've had a person reach out before for a similar issue, and they had a totem in their off-hand, so make sure you have nothing in your off-hand!

I'll put this on my to-do to fix, so off-hand doesn't matter! apologies for the bug!
