### ISSUE TITLE
Conflicting recipes with Farmers Delight

### ISSUE THREAD

**Issue by JedaiGames** [OopsOnlyDelta/redeco#9]
**Is your feature request related to a problem? Please describe.**
This mod have recipe crossing issue. Cabinet from this mod and Farmer's Delight have the same recipe, with Farmers delight being concidered as priority. It leads to the player being unable to craft Cabinets from Re:Deco, and Cabinet Counter, wich uses simple Cabinet in it.

**Describe the solution you'd like**
You already have Polished planks and slabs in your mod, and seems like all furniture use its teksture anyways. Maybe made that all wooden furniture simply use Polished variant of planks instead of vanila ones? 

**Describe alternatives you've considered**
At least, make it possible to use Farmer's Delight Cabinet in Cabinet Counter recipes please.

**Additional context**
![image](https://github.com/OopsOnlyDelta/redeco/assets/63721354/c4af692d-194b-4bb3-a26a-a6d45a8f37cc)
![image](https://github.com/OopsOnlyDelta/redeco/assets/63721354/b0c44e80-23e2-4618-9221-215750cd03df)

**Comment by OopsOnlyDelta** [comment]
Noted! I'll figure out a solution, be it compatibility or changing mine. 

in the meantime, here's a mod that lets you switch the recipe output for matching recipes:
https://www.curseforge.com/minecraft/mc-mods/polymorph
